### ISSUE TITLE
Single Measurement - Unreliable 

### ISSUE THREAD

**Issue by Andeloth** [BYUCamachoLab/DAQ-and-laser-API#3]
Single Measurement sometimes doesn't work:
- repeating "Failed to Read wavelength point"
- the following error (plot still shows up and data is saved though)

Exception ignored in: <bound method NIDAQInterface.__del__ of <DAQinterface.NIDAQInterface object at 0x0000012D384470F0>>
Traceback (most recent call last):
  File "C:\Users\camacho\Documents\Measurement Scripts\DAQ-and-laser-API\DAQinterface.py", line 62, in __del__
  File "C:\ProgramData\Miniconda3\lib\site-packages\nidaqmx\task.py", line 475, in close
  File "C:\ProgramData\Miniconda3\lib\site-packages\nidaqmx\errors.py", line 115, in check_for_error
ModuleNotFoundError: import of nidaqmx._lib halted; None in sys.modules
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\nidaqmx\task.py", line 105, in __del__
  File "C:\ProgramData\Miniconda3\lib\site-packages\nidaqmx\task.py", line 156, in name
  File "C:\ProgramData\Miniconda3\lib\site-packages\nidaqmx\errors.py", line 115, in check_for_error
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by Andeloth** [comment]
Fixed.
